
version: '3'


services: 
  # db:
  #   image: postgres:14.4
  #   restart: always
  #   ports:
  #     - "${DB_PORT}:${DB_PORT}"
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   container_name: anylistDB
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data

  anylistapp:
    # depends_on:
    #   - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: klerith/nest-graphql-prod
    container_name: AnylistApp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"

    environment:
      STATE: ${STATE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
